#include <inttypes.h>
#include <oilconfig.h>

#if OIL_BYTE_ORDER == OIL_BIG_ENDIAN
# define LDF "ldl"         /* load from the address forward */
# define SDF "sdl"         /* store to the address forward*/
# define LDB "ldr"         /* load from the address + 1byte backward*/
# define SDB "sdr"         /* store to the address + 1byte backward */
#else
# define LDF "ldr"
# define SDF "sdr"
# define LDB "ldl"
# define SDB "sdl"
#endif

void oil_copy8x8_u8_gs2f (uint8_t *dest, int dstr, uint8_t *src, int sstr)
{
    __asm__ __volatile__ (
        ".set       mips3                       \n\t"
        "andi      $24, %1, 0x7                 \n\t"
        "bne        $24, $0, ld_unaligned       \n\t"
        "andi      $25, %0, 0x7                 \n\t"
        "ld_aligned:                            \n\t"
        "ld         $8, 0(%1)                   \n\t"
        "addu       %1, %1, %2                  \n\t"
        "ld         $9, 0(%1)                   \n\t"
        "addu       %1, %1, %2                  \n\t"
        "ld         $10, 0(%1)                  \n\t"
        "addu       %1, %1, %2                  \n\t"
        "ld         $11, 0(%1)                  \n\t"
        "addu       %1, %1, %2                  \n\t"
        "ld         $12, 0(%1)                  \n\t"
        "addu       %1, %1, %2                  \n\t"
        "ld         $13, 0(%1)                  \n\t"
        "addu       %1, %1, %2                  \n\t"
        "ld         $14, 0(%1)                  \n\t"
        "addu       %1, %1, %2                  \n\t"
        "ld         $15, 0(%1)                  \n\t"
        "bne        $25, $0, sd_unaligned       \n\t"
        "nop                                    \n\t"
        "sd_aligned:                            \n\t"
        "sd         $8, 0(%0)                   \n\t"
        "addu       %0, %0, %3                  \n\t"
        "sd         $9, 0(%0)                   \n\t"
        "addu       %0, %0, %3                  \n\t"
        "sd         $10, 0(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        "sd         $11, 0(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        "sd         $12, 0(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        "sd         $13, 0(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        "sd         $14, 0(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        "sd         $15, 0(%0)                  \n\t"
        "j          finished                    \n\t"
        "nop                                    \n\t"
        "ld_unaligned:                          \n\t"
        LDF"        $8, 0(%1)                   \n\t"
        LDB"        $8, 7(%1)                   \n\t"
        "addu       %1, %1, %2                  \n\t"
        LDF"        $9, 0(%1)                   \n\t"
        LDB"        $9, 7(%1)                   \n\t"
        "addu       %1, %1, %2                  \n\t"
        LDF"        $10, 0(%1)                  \n\t"
        LDB"        $10, 7(%1)                  \n\t"
        "addu       %1, %1, %2                  \n\t"
        LDF"        $11, 0(%1)                  \n\t"
        LDB"        $11, 7(%1)                  \n\t"
        "addu       %1, %1, %2                  \n\t"
        LDF"        $12, 0(%1)                  \n\t"
        LDB"        $12, 7(%1)                  \n\t"
        "addu       %1, %1, %2                  \n\t"
        LDF"        $13, 0(%1)                  \n\t"
        LDB"        $13, 7(%1)                  \n\t"
        "addu       %1, %1, %2                  \n\t"
        LDF"        $14, 0(%1)                  \n\t"
        LDB"        $14, 7(%1)                  \n\t"
        "addu       %1, %1, %2                  \n\t"
        LDF"        $15, 0(%1)                  \n\t"
        LDB"        $15, 7(%1)                  \n\t"
        "beq        $25, $0, sd_aligned         \n\t"
        "nop                                    \n\t"
        "sd_unaligned:                          \n\t"
        SDF"        $8, 0(%0)                   \n\t"
        SDB"        $8, 7(%0)                   \n\t"
        "addu       %0, %0, %3                  \n\t"
        SDF"        $9, 0(%0)                   \n\t"
        SDB"        $9, 7(%0)                   \n\t"
        "addu       %0, %0, %3                  \n\t"
        SDF"        $10, 0(%0)                  \n\t"
        SDB"        $10, 7(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        SDF"        $11, 0(%0)                  \n\t"
        SDB"        $11, 7(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        SDF"        $12, 0(%0)                  \n\t"
        SDB"        $12, 7(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        SDF"        $13, 0(%0)                  \n\t"
        SDB"        $13, 7(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        SDF"        $14, 0(%0)                  \n\t"
        SDB"        $14, 7(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        SDF"        $15, 0(%0)                  \n\t"
        SDB"        $15, 7(%0)                  \n\t"
        "addu       %0, %0, %3                  \n\t"
        "finished:                              \n\t"
        :   "+r" (dest)
        :   "r" (src),
            "r" (sstr),
            "r" (dstr)
        :   "memory", "$8", "$9", "$10", "$11", "$12", "$13", "$14", "$15", "$24", "$25"
    ); 
}

